replicaCount: 1

image:
  repository: nginx
  tag: "1.24"
  pullPolicy: IfNotPresent

appName: notes-app
environment: development

containerPort: 80

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30090
